import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';
import { Home, Settings, LogOut, ShieldAlert, BookOpen, Wine, ClipboardList } from 'lucide-react';
import { getUser } from '@/lib/auth';

export default async function RootLayout({ children }) {
  const user = await getUser();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col bg-[#0a0a0a] text-white">
        <nav className="sticky top-0 z-40 w-full backdrop-blur flex-none border-b border-gray-800 bg-[#0a0a0a]/80">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 items-center justify-between">
              <Link href="/" className="flex items-center gap-2 text-gray-300 hover:text-white transition-colors group">
                <div className="bg-blue-600/20 p-2 rounded-lg group-hover:bg-blue-600/40 transition-colors">
                  <Home className="w-5 h-5 text-blue-400" />
                </div>
                <span className="font-semibold tracking-wide">Home Catalog</span>
              </Link>
              
              <div className="flex items-center gap-6">
                <Link href="/variance" className="flex items-center gap-2 text-sm font-medium text-gray-400 hover:text-blue-400 transition-colors">
                  <Wine className="w-4 h-4 text-emerald-400" />
                  <span className="hidden sm:inline">Auditor</span>
                </Link>

                <Link href="/changelog" className="flex items-center gap-2 text-sm font-medium text-gray-400 hover:text-blue-400 transition-colors">
                  <BookOpen className="w-4 h-4" />
                  <span className="hidden sm:inline">Changelog</span>
                </Link>

                <div className="text-sm font-medium text-gray-500 bg-gray-900 px-3 py-1 rounded-full border border-gray-800 hidden md:block">
                  Beta 1.5.1
                </div>

                {user && (
                  <div className="flex items-center gap-3 border-l border-gray-800 pl-4">
                    {user.isAdmin === 1 && (
                      <Link href="/admin" className="flex items-center gap-2 text-sm text-blue-400 hover:text-blue-300 transition-colors">
                        <ShieldAlert className="w-4 h-4" />
                        <span className="hidden sm:inline">Admin</span>
                      </Link>
                    )}
                    <Link href="/settings" className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors">
                      <Settings className="w-4 h-4" />
                      <span className="hidden sm:inline">Settings</span>
                    </Link>
                    <form action="/api/auth/logout" method="POST">
                      <button type="submit" className="flex items-center gap-2 text-sm text-red-400 hover:text-red-300 transition-colors">
                        <LogOut className="w-4 h-4" />
                        <span className="hidden sm:inline">Logout</span>
                      </button>
                    </form>
                  </div>
                )}
              </div>
            </div>
          </div>
        </nav>
        <div className="flex-1">
          {children}
        </div>
      </body>
    </html>
  );
}
